apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  player_initial_live: "3"
  ui_properties_file_name: "user-interface.properties"
  loglevel: debug
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-live=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true